---
version: 2

dist: ./.dist

checksum:
  name_template: checksums.txt

builds:
  - id: clabverter
    binary: clabverter
    main: ./cmd/clabverter/main.go
    env:
      - CGO_ENABLED=0
      - VERSION={{ .Env.RELEASE_VERSION }}
    ldflags:
      - -s -w -X github.com/srl-labs/clabernetes/constants.Version={{ .Env.VERSION }}
    flags:
      - -trimpath
      - -a
    goos:
      - linux
      - darwin

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip

# we just wanna build/archive w/ goreleaser, disable changelog/release bits
changelog:
  disable: true
release:
  disable: true