apiVersion: clabernetes.containerlab.dev/v1alpha1
kind: Connectivity
metadata:
  labels:
    clabernetes/app: clabernetes
    clabernetes/name: topology-basic
    clabernetes/topologyKind: containerlab
    clabernetes/topologyOwner: topology-basic
  name: topology-basic
  namespace: NAMESPACE
spec:
  pointToPointTunnels:
    srl1:
      - destination: topology-basic-srl2-vx.NAMESPACE.svc.cluster.local
        localInterface: e1-1
        localNode: srl1
        remoteInterface: e1-1
        remoteNode: srl2
        tunnelID: 1
      - destination: topology-basic-host-vx.NAMESPACE.svc.cluster.local
        localInterface: e1-3
        localNode: srl1
        remoteInterface: eth13
        remoteNode: host
        tunnelID: 2
    srl2:
      - destination: topology-basic-srl1-vx.NAMESPACE.svc.cluster.local
        localInterface: e1-1
        localNode: srl2
        remoteInterface: e1-1
        remoteNode: srl1
        tunnelID: 1
status: {}
