{{- if .Values.globalConfig.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    revision: "{{ .Release.Revision }}"
    clabernetes/app: {{ .Values.appName }}
    clabernetes/name: "{{ .Values.appName }}-config"
    clabernetes/component: config
    {{- if .Values.globalLabels }}
{{ .Values.globalLabels | toYaml | indent 4 }}
    {{- end }}
  {{- if .Values.globalAnnotations }}
  annotations:
{{ .Values.globalAnnotations | toYaml | indent 4 }}
  {{- end }}
data:
  mergeMode: {{ .Values.globalConfig.mergeMode }}
  globalAnnotations: |-
    ---
{{ .Values.globalAnnotations | toYaml | indent 4 }}
  globalLabels: |-
    ---
{{ .Values.globalLabels | toYaml | indent 4 }}
  resourcesDefault: |-
    ---
{{ .Values.globalConfig.deployment.resourcesDefault | toYaml | indent 4 }}
  resourcesByContainerlabKind: |-
    ---
{{ .Values.globalConfig.deployment.resourcesByContainerlabKind | toYaml | indent 4 }}
  nodeSelectorsByImage: |-
{{ .Values.globalConfig.deployment.nodeSelectorsByImage | toYaml | indent 4 }}
    ---
  privilegedLauncher: "{{ .Values.globalConfig.deployment.privilegedLauncher }}"
  containerlabDebug: "{{ .Values.globalConfig.deployment.containerlabDebug }}"
  {{- if .Values.globalConfig.deployment.containerlabTimeout }}
  containerlabTimeout: {{ .Values.globalConfig.deployment.containerlabTimeout }}
  {{- end }}
  {{- if .Values.globalConfig.deployment.containerlabVersion }}
  containerlabVersion: {{ .Values.globalConfig.deployment.containerlabVersion }}
  {{- end }}
  inClusterDNSSuffix: {{ .Values.globalConfig.inClusterDNSSuffix }}
  imagePullThroughMode: {{ .Values.globalConfig.imagePull.imagePullThroughMode }}
  {{- if .Values.globalConfig.deployment.launcherImage }}
  launcherImage: {{ .Values.globalConfig.deployment.launcherImage }}
  {{- end }}
  launcherImagePullPolicy: {{ .Values.globalConfig.deployment.launcherImagePullPolicy }}
  launcherLogLevel: {{ .Values.globalConfig.deployment.launcherLogLevel }}
  {{- if .Values.globalConfig.imagePull.criSockOverride }}
  criSockOverride: {{ .Values.globalConfig.imagePull.criSockOverride }}
  {{- end }}
  {{- if .Values.globalConfig.imagePull.criKindOverride }}
  criKindOverride: {{ .Values.globalConfig.imagePull.criKindOverride }}
  {{- end }}
  naming: {{ .Values.globalConfig.naming }}
  {{- if .Values.globalConfig.deployment.extraEnv }}
  extraEnv: |-
{{ .Values.globalConfig.deployment.extraEnv | toYaml | indent 4 }}
  {{- end }}
{{- end }}